name: Verify
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  node:
    name: Node
    uses: curium-rocks/flows/.github/workflows/node-ts.yml@main
    secrets: 
      SONARQUBE_KEY: ${{ secrets.SONARQUBE_KEY }}
